# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec74fe3b1e1e760dce85e09dfb3a6b9bb8c670b3c141080ad518a0b463820612db17d857a812b912f1741542ac414b4004758f48f9b3c64b9f8e6fdc360fb955

test:
  secret_key_base: bd2df4021617799bb0fc8965cc34f054f5e9c12e85397ca866f992e58138207c82f63be54f2d05cd741b74782448abd4ff03bcb83d12ae8508376ed664f05e40

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
